/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/layouts/AppBar.vue')['default']
    AppBreadcrumbs: typeof import('./src/layouts/AppBreadcrumbs.vue')['default']
    AppDrawer: typeof import('./src/layouts/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/layouts/AppFooter.vue')['default']
    AppMain: typeof import('./src/layouts/AppMain.vue')['default']
    AppSpinner: typeof import('./src/layouts/AppSpinner.vue')['default']
    BaseFormCheckbox: typeof import('./src/components/BaseFormCheckbox.vue')['default']
    BaseFormCombo: typeof import('./src/components/BaseFormCombo.vue')['default']
    BaseFormField: typeof import('./src/components/BaseFormField.vue')['default']
    Combo: typeof import('./src/components/Combo.vue')['default']
    copy: typeof import('./src/layouts/AppFooter copy.vue')['default']
    DashBoard: typeof import('./src/components/DashBoard.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
