/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./layouts/AppBar.vue')['default']
    AppDrawer: typeof import('./layouts/AppDrawer.vue')['default']
    AppFooter: typeof import('./layouts/AppFooter.vue')['default']
    AppMain: typeof import('./layouts/AppMain.vue')['default']
    Component: typeof import('./components/SearchBar.vue')['default']
    DashBoard: typeof import('./components/DashBoard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
