/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/Login/': RouteRecordInfo<'/Login/', '/Login', Record<never, never>, Record<never, never>>,
    '/Signup/': RouteRecordInfo<'/Signup/', '/Signup', Record<never, never>, Record<never, never>>,
    '/System/help-management/': RouteRecordInfo<'/System/help-management/', '/System/help-management', Record<never, never>, Record<never, never>>,
    '/System/help-management/index-info/imageInfo': RouteRecordInfo<'/System/help-management/index-info/imageInfo', '/System/help-management/index-info/imageInfo', Record<never, never>, Record<never, never>>,
    '/System/help-management/index-info/indexInfo': RouteRecordInfo<'/System/help-management/index-info/indexInfo', '/System/help-management/index-info/indexInfo', Record<never, never>, Record<never, never>>,
    '/System/help-management/index-info/slideItem': RouteRecordInfo<'/System/help-management/index-info/slideItem', '/System/help-management/index-info/slideItem', Record<never, never>, Record<never, never>>,
    '/System/help-management/indexTree': RouteRecordInfo<'/System/help-management/indexTree', '/System/help-management/indexTree', Record<never, never>, Record<never, never>>,
    '/System/member-management/': RouteRecordInfo<'/System/member-management/', '/System/member-management', Record<never, never>, Record<never, never>>,
    '/System/member-management/indexList': RouteRecordInfo<'/System/member-management/indexList', '/System/member-management/indexList', Record<never, never>, Record<never, never>>,
    '/System/member-management/popupCreate': RouteRecordInfo<'/System/member-management/popupCreate', '/System/member-management/popupCreate', Record<never, never>, Record<never, never>>,
    '/System/member-management/popupResetPassword': RouteRecordInfo<'/System/member-management/popupResetPassword', '/System/member-management/popupResetPassword', Record<never, never>, Record<never, never>>,
    '/System/member-management/popupUpdate': RouteRecordInfo<'/System/member-management/popupUpdate', '/System/member-management/popupUpdate', Record<never, never>, Record<never, never>>,
    '/System/menu-management/': RouteRecordInfo<'/System/menu-management/', '/System/menu-management', Record<never, never>, Record<never, never>>,
    '/System/menu-management/indexInfo': RouteRecordInfo<'/System/menu-management/indexInfo', '/System/menu-management/indexInfo', Record<never, never>, Record<never, never>>,
    '/System/menu-management/indexTree': RouteRecordInfo<'/System/menu-management/indexTree', '/System/menu-management/indexTree', Record<never, never>, Record<never, never>>,
    '/System/menu-management-returnobject/': RouteRecordInfo<'/System/menu-management-returnobject/', '/System/menu-management-returnobject', Record<never, never>, Record<never, never>>,
    '/System/menu-management-returnobject/indexInfo': RouteRecordInfo<'/System/menu-management-returnobject/indexInfo', '/System/menu-management-returnobject/indexInfo', Record<never, never>, Record<never, never>>,
    '/System/menu-management-returnobject/indexTree': RouteRecordInfo<'/System/menu-management-returnobject/indexTree', '/System/menu-management-returnobject/indexTree', Record<never, never>, Record<never, never>>,
  }
}
